spring:
  application.name: "demo"
  rabbitmq:
    broker-url: "127.0.0.1"
    username: "classic-user"
    password: "classic-password"

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 100
      minimum-idle: 2
  jpa.hibernate.ddl-auto: update